// Python Programming Quiz — full question bank
// Each option array; `answer` is the 0-based index of the correct option.
const QUIZ_DATA = {
"Section 1: Python Basics": [
{q:"What do we use to define a block of code in Python language?", options:["Key","Brackets","Indentation","None of these"], answer:2},
{q:"Which one of the following is the correct extension of the Python file?", options:[".py",".python",".p","None of these"], answer:0},
{q:"Who developed the Python language?", options:["Zim Den","Guido van Rossum","Niene Stom","Wick van Rossum"], answer:1},
{q:"Is Python case sensitive when dealing with identifiers?", options:["No","Yes"], answer:1},
{q:"What does pip stand for python?", options:["Pip Installs Python","Pip Installs Packages","Preferred Installer Program","All of the mentioned"], answer:1},
{q:"Which one of the following is not a keyword in Python language?", options:["pass","eval","assert","nonlocal"], answer:1, note:"eval is a built-in function, not a keyword; pass, assert, nonlocal are keywords."},
{q:"What is the return type of function id?", options:["int","float","bool","dict"], answer:0},
{q:"Which character is used in Python to make a single line comment?", options:["/","//","#","##"], answer:2},
{q:"__________ is a immutable object.", options:["List","Dictionary","set","Integer"], answer:3},
{q:"Which Anaconda component is a popular integrated development environment (IDE) for data science and scientific computing?", options:["Jupyter Notebook","Matplotlib","Conda","Spyder"], answer:3},
{q:"Anaconda is available for which of the following operating systems?", options:["Windows","Linux","MacOS","All of these"], answer:3},
{q:"Which Anaconda component is responsible for managing packages and environments?", options:["Jupyter Notebook","Matplotlib","Conda","Spyder"], answer:2},
{q:"What command is used to install a new Python package or library using Anaconda's package manager?", options:["pip install","conda update","conda install","pip update"], answer:2},
{q:"Which of the following is not a Python data science library commonly included in Anaconda?", options:["NumPy","Pandas","Matplotlib","Django"], answer:3, note:"Django is a web framework, not a data science library."},
{q:"Which of the following programming languages is not natively supported by Spyder?", options:["Python","R","C++","Julia"], answer:2, note:"Spyder is a Python-focused IDE."},
{q:"Spyder is particularly well-suited for which type of tasks?", options:["Game development","Web development","Data science and scientific computing","Mobile app development"], answer:2},
{q:"What is the default Python code editor in Spyder?", options:["Jupyter Notebook","Visual Studio Code","Sublime Text","The built-in editor"], answer:3},
{q:"Which pane in Spyder allows you to view and navigate your project's directory structure and files?", options:["Variable Explorer","IPython Console","Editor","File Explorer"], answer:3},
],
"Section 2: Identifiers, Data Types & Operators": [
{q:"All keywords in Python are in _________", options:["Capitalized","lower case","UPPER CASE","None of the mentioned"], answer:1},
{q:"Special symbols are allowed in identifiers.", options:["TRUE","FALSE"], answer:1},
{q:"Which statement is TRUE for Strings?", options:["String are immutable","String are mutable","String allow Update operation","None of these"], answer:0},
{q:"What data type is the object below? L = [1, 23, 'hello', 1]", options:["List","Dictionary","Array","Tuple"], answer:0},
{q:"In order to store values in terms of key and value we use what core data type.", options:["List","Dictionary","Array","Tuple"], answer:1},
{q:"What is the maximum possible length of an identifier?", options:["16","32","64","Not defined"], answer:3},
{q:"Amongst which of the following is / are the Numeric Types of Data Types?", options:["int","float","complex","All of these"], answer:3},
{q:"Which of these is not a core data type?", options:["list","tuple","dictionary","class"], answer:3},
{q:"Variable name cannot be start with digits.", options:["TRUE","FALSE"], answer:0},
{q:"Keywords cannot be used as an identifiers.", options:["TRUE","FALSE"], answer:0},
{q:"What will be the output of the following code snippet? print(2**3 + (5 + 6)**(1 + 1))", options:["129","30","33","130"], answer:0, note:"2**3=8, (5+6)**(1+1)=11**2=121, 8+121=129"},
{q:"Which is the correct operator for power(xy)?", options:["X^y","X**y","X^^y","None of these"], answer:1},
{q:"Which one of these is floor division?", options:["/","//","%","**"], answer:1},
{q:"What is the answer to this expression, 22 % 3 is?", options:["7","1","0","5"], answer:1},
{q:"____ and _____ are identity operators in python", options:["is, is not","in, not in","**, //","None of these"], answer:0},
],
"Section 3: Operators, Loops & Conditionals": [
{q:"Operators with the same precedence are evaluated in which manner?", options:["Left to Right","Right to Left","Can't say","None of these"], answer:0},
{q:"Which one of the following has the highest precedence in the expression?", options:["Exponential","Addition","Multiplication","Parentheses"], answer:3},
{q:"Which arithmetic operators can we NOT use with strings?", options:["+","-","*","None of these"], answer:1},
{q:"What will be the result of the following expression in Python “2 ** 3 + 5 ** 2”?", options:["33","100","16","31"], answer:0, note:"2**3=8, 5**2=25, 8+25=33"},
{q:"____ and _____ are membership operators in python", options:["is, is not","in, not in","**, //","None of these"], answer:1},
{q:"Which of the following types of loops are not supported in Python?", options:["for","while","do-while","None of these"], answer:2},
{q:"The ________ statement is a null operation.", options:["break","exit","return","pass"], answer:3},
{q:"Which statement will check if a is equal to b?", options:["if a==b","if a==b:","if a===b:","if a=b:"], answer:1},
{q:"What keyword would you use to add an alternative condition to an if statement?", options:["Else if","elif","elseif","None of these"], answer:1},
{q:"What will be the output of the following Python code snippet? x = 2\nfor i in range(x): x += 1\nprint (x)", options:["0 1 2 3 4","0 1","3 4","1 2 3 4"], answer:2, note:"range(x) is evaluated once as range(2) -> 2 iterations; x goes 2->3->4; printed value is 4 (closest listed option)."},
{q:"What will be the output of the following Python code snippet? for i in [1, 2, 3, 4][::-1]: print (i)", options:["1 2 3 4","4 3 2 1","error","none of the mentioned"], answer:1},
{q:"What will be the output of the following Python code? for i in range(2.0): print(i)", options:["0.0 1.0","1","error","None of these"], answer:2, note:"range() requires an integer argument."},
{q:"What will be the output of the following Python code? x = \"abcdef\"\nwhile i in x: print(i, end=\" \")", options:["abcdef","a b c d e f","Error","None of these"], answer:2, note:"'i' is not defined before use in the while condition."},
{q:"What will be the output of the following Python code? for i in range(0): print(i)", options:["0","no output","Error","None of these"], answer:1},
{q:"What will be the output of the following Python code? True = False\nwhile True: print(True)\nbreak", options:["TRUE","FALSE","Error","None of these"], answer:2, note:"True/False are keywords/constants in Python 3 and cannot be reassigned (SyntaxError)."},
],
"Section 4: Strings & Functions": [
{q:"Which of the following will give \"Simon\" as output? For a given string:- “John,Simon,Aryan”", options:["print(str1[-7:-12])","print(str1[-11:-7])","print(str1[-11:-6])","print(str1[-7:-11])"], answer:2},
{q:"Which of the following will give \"Aryan\" as output? For a given string:- “John,Simon,Aryan”", options:["print(str1[-7:-12])","print(str1[-6:-1])","print(str1[-5:])","print(str1[-7:-11])"], answer:2},
{q:"What will be the output of the following Python code? print(max(\"what are you\"))", options:["error","u","t","y"], answer:3, note:"max() on a string compares characters by ASCII value; 'y' is highest."},
{q:"Given a string example=”hello” what is the output of example.count('l')?", options:["2","1","0","None"], answer:0},
{q:"What will be the output of the following Python statement? print(chr(ord('A')))", options:["A","B","a","None"], answer:0},
{q:"Which of the following keywords is used for function declaration in Python language?", options:["Function_name","def","define","None of these"], answer:1},
{q:"Python supports the creation of anonymous functions at runtime, using a construct called __________", options:["pi","anonymous","lambda","None of these"], answer:2},
{q:"Which one of the following is the use of function in python?", options:["Functions don't provide better modularity for your application","you can't also create your own functions","Functions are reusable pieces of programs","All of the mentioned"], answer:2},
{q:"What are the two main types of functions in Python?", options:["System function","Custom function","Built-in function & User defined function","User function"], answer:2},
{q:"Which of the following is a feature of DocString?", options:["Provide a convenient way of associating documentation with Python modules, functions, classes, and methods","All functions should have a docstring","Docstrings can be accessed by the __doc__ attribute on objects","All of the mentioned"], answer:3},
{q:"What is a variable defined outside a function referred to as?", options:["A global variable","A volatile variable","A local variable","An automatic variable"], answer:0},
{q:"Where is function defined?", options:["Module","Class","Another function","All of the mentioned"], answer:3},
{q:"What is a variable defined inside a function referred to as?", options:["A global variable","A volatile variable","A local variable","An automatic variable"], answer:2},
{q:"Does Lambda contains return statements?", options:["TRUE","FALSE"], answer:1, note:"Lambda implicitly returns the expression; it does not use an explicit return statement."},
{q:"Which are the advantages of functions in python?", options:["Reducing duplication of code","Decomposing complex problems into simpler pieces","Improving clarity of the code","All of the mentioned"], answer:3},
],
"Section 5: Lists, Tuples, Sets & Dictionaries": [
{q:"Which function is used to add a new element into a list at specific index?", options:["Append()","Insert()","Add()","None of these"], answer:1},
{q:"Which function is used to add a new element into a list at end position?", options:["Append()","Insert()","Add()","None of these"], answer:0},
{q:"Which of the following method is used to delete a data item from list using index and return deleted value?", options:["Pop()","Del statement","Remove()","None of these"], answer:0},
{q:"__________ is a mutable object.", options:["String","List","Tuple","Integer"], answer:1},
{q:"Which of the following method is used to delete a data item from list using index?", options:["Pop()","Del statement","Remove()","Both A and B"], answer:3},
{q:"What is the output when we execute list(“hello”)?", options:["['h', 'e', 'l', 'l', 'o']","['hello']","['llo']","['olleh']"], answer:0},
{q:"Suppose list1 is [4, 2, 2, 4, 5, 2, 1, 0], Which of the following is correct syntax for slicing operation?", options:["print(list1[2:])","print(list1[:2])","print(list1[:-2])","all of the mentioned"], answer:3},
{q:"Suppose list1 is [1, 3, 2], What is list1 * 2?", options:["[2, 6, 4]","[1, 3, 2, 1, 3]","[1, 3, 2, 1, 3, 2]","[1, 3, 2, 3, 2, 1]"], answer:2},
{q:"To insert 5 to the third position in list1, we use which command?", options:["list1.insert(3, 5)","list1.insert(2, 5)","list1.add(3, 5)","list1.append(3, 5)"], answer:1},
{q:"Suppose list1 is [3, 4, 5, 20, 5, 25, 1, 3], what is list1.count(5)?", options:["1","2","3","4"], answer:1},
{q:"In dictionary, Keys are _______ objects.", options:["immutable","mutable","Both A and B","None of these"], answer:0},
{q:"What is the data type of (1)?", options:["Tuple","Integer","List","None of these"], answer:1, note:"A single value in parentheses without a comma is not a tuple."},
{q:"If a=(1,2,3,4), a[1:-1] is _________", options:["Error, tuple slicing doesn't exist","[2,3]","(2,3,4)","(2,3)"], answer:3},
{q:"Which of the following is not the correct syntax for creating a set?", options:["set([[1,2],[3,4]])","set([1,2,2,3,4])","set((1,2,3,4))","{1,2,3,4}"], answer:0, note:"Lists are unhashable/mutable, so they can't be set elements."},
{q:"Suppose t = (10,12,33,43), which of the following statement is incorrect?", options:["print(t[2])","print(max(t))","print(min(t))","t[2]=45"], answer:3, note:"Tuples are immutable."},
{q:"Which of the following statements is used to create an empty set?", options:["{}","set( )","[]","()"], answer:1, note:"{} creates an empty dictionary, not a set."},
{q:"If a={5,6,7,8}, which of the following statements is false?", options:["print(len(a))","print(min(a))","a.remove(5)","a[2]=45"], answer:3, note:"Sets don't support indexing."},
{q:"Suppose d = “john”:40, “peter”:45. To obtain the number of entries in dictionary which command do we use?", options:["d.size()","len(d)","size(d)","d.len()"], answer:1},
{q:"What is the output of code? t=(9,8,7,6,5,4)\nprint(t[:-3])", options:["(9, 8, 7)","(9, 8, 7, 6)","(4, 5, 6)","None of these"], answer:0},
{q:"In dictionary, Values are _______ objects.", options:["immutable","mutable","Both A and B","None of these"], answer:1},
{q:"Which function is used to check the data type of variable?", options:["type()","id()","len()","Sum()"], answer:0},
{q:"What will be the output of the following Python function? print(all([2,4,0,6]))", options:["TRUE","FALSE","0","Error"], answer:1, note:"0 is falsy, so all() returns False."},
{q:"What will be the output of the following Python expression? print(round(4.5676,2))", options:["4.55","4.56","4.57","5"], answer:2},
{q:"Which function is used to sort the list parmanently?", options:["sort( )","sorted( )","reverse( )","None of these"], answer:0},
{q:"Which of the following functions does not necessarily accept only iterables as arguments?", options:["all( )","max( )","min( )","chr( )"], answer:3, note:"chr() takes a single integer, not an iterable."},
{q:"______ function cannot work with tuples.", options:["count( )","index( )","reverse( )","len( )"], answer:2, note:"Tuples are immutable and have no reverse() method."},
{q:"Which of the following functions accepts only integers as arguments?", options:["all( )","max( )","min( )","chr( )"], answer:3},
{q:"Which of the following functions will not result in an error when no arguments are passed to it?", options:["min ( )","max( )","float( )","all( )"], answer:2, note:"float() with no arguments returns 0.0."},
{q:"Which function is used to sort the list temporary?", options:["sort( )","sorted( )","reverse( )","None of these"], answer:1},
{q:"What will be the output of the following Python function? print( min(max(False,-3,-4), 2,7))", options:["2","-3","-4","FALSE"], answer:3, note:"max(False,-3,-4)=False (since False==0 > -3,-4); min(False,2,7)=False."},
],
"Section 6: File Handling": [
{q:"To open a file for both reading and writing without erasing its content, which mode would you use?", options:["w+","a+","r+","None of these"], answer:2},
{q:"If you want to append data to an existing file without erasing its content, which mode should you use?", options:["w+","a","r+","None of these"], answer:1},
{q:"What does the 'b' in file modes such as 'rb' or 'wb' stand for?", options:["Binary","Byte","Before","Bit"], answer:0},
{q:"Which function is used to open a file in Python?", options:["file.open()","openfile()","open()","None of these"], answer:2},
{q:"Which method is used to write a list of strings to a file?", options:["write()","writelines()","writelist()","None of these"], answer:1},
{q:"Which statement ensures that a file is properly closed after its suite finishes, even if an exception is raised?", options:["finally","with","ensure","try:.. Except:…"], answer:1},
{q:"Which of the following is a valid way to open a file in binary mode for reading?", options:["open('file.txt', 'br')","open('file.txt', 'rb')","open('file.txt', 'r+b')","open('file.txt', 'b')"], answer:1},
{q:"Which method is used to read all lines of a file into a list?", options:["read()","readline()","readlines()","readall()"], answer:2},
{q:"Which mode should be used to open a file for writing, creating the file if it does not exist, and truncating the file if it exists?", options:["w","a+","r+","w+"], answer:0},
{q:"What is the default mode in which the open() function opens a file?", options:["read mode","write mode","append mode","None of these"], answer:0},
{q:"How do you close a file in Python?", options:["file.close()","file(close)","file.closer()","None if these"], answer:0},
{q:"Which method is used to read the entire content of a file as a string?", options:["read()","readline()","readlines()","readall()"], answer:0},
{q:"How do you open a file for appending in binary mode?", options:["open('file.txt', 'ab')","open('file.txt', 'a')","open('file.txt', 'wb')","open('file.txt', 'rb')"], answer:0},
{q:"Which method is used to write a single line into a file?", options:["write()","writelines()","writelist()","None of these"], answer:0},
{q:"Which method is used to read a single line from a file?", options:["read()","readline()","readlines()","readall()"], answer:1},
],
"Section 7: Exception Handling": [
{q:"In Python, find which one isn’t an exception handling keyword.", options:["try","except","finally,","accept"], answer:3},
{q:"Which block lets you test a block of code for errors?", options:["try","except","finally","None of these"], answer:0},
{q:"What keyword is used in Python to raise exceptions?", options:["raise","try","goto","except"], answer:0},
{q:"How many except statements can a try-except block have?", options:["Zero","One","More than one","None of these"], answer:2},
{q:"When will the else part of try-except-else be executed?", options:["always","When exception occurs","When no exception occurs","None of these"], answer:2},
{q:"Which of the following blocks will always be executed whether an exception is encountered or not in a program?", options:["try","except","finally","None of these"], answer:2},
{q:"Can one block of except statements handle multiple exception?", options:["Yes","No"], answer:0},
{q:"What happens when ‘1’ == 1 is executed?", options:["we get a True","we get a False","an TypeError occurs","a ValueError occurs"], answer:1},
{q:"What will be the output of the following Python code? lst = [1, 2, 3]\nprint(lst[3])", options:["NameError","ValueError","IndexError","TypeError"], answer:2},
{q:"What will be the output of the following Python code, if the time module has already been imported? print(4 + '3')", options:["NameError","ValueError","IndexError","TypeError"], answer:3},
{q:"What is the purpose of the assert statement in Python?", options:["To raise a SyntaxError","To terminate the program","To ensure a condition returns True","To handle exceptions silently"], answer:2},
{q:"What does the EOFError stand for?", options:["End Of File Error","Execution Of Function Error","External Output Failure Error","None of the above"], answer:0},
{q:"Which of the following is the correct syntax to handle an exception in Python?", options:["try: ... except: …","try: ... catch: …","try: ... handle: …","try: ... finally: …"], answer:0},
{q:"Which of the following exceptions is raised when an undefined variable is accessed?", options:["TypeError","KeyError","NameError","ValueError"], answer:2},
{q:"How do you raise an exception in Python?", options:["raise ExceptionName","throw ExceptionName","catch ExceptionName","assert ExceptionName"], answer:0},
],
"Section 8: Object-Oriented Programming": [
{q:"The method to wrap data into one unit:", options:["Encapsulation","Inheritance","Polymorphism","Abstraction"], answer:0},
{q:"Which of the following is not a category of inheritance?", options:["Single level","Multi level","Multiple","Double level"], answer:3},
{q:"When a child class inherits from only one parent class, it is called?", options:["Single inheritance","Multiple inheritance","Multilevel inheritance","None of these"], answer:0},
{q:"You can delete properties on objects by using the ______ keyword.", options:["delete","deld","del","drop"], answer:2},
{q:"__________function that will make the child class inherit all the methods and properties from its parent.", options:["self","super","Both A and B","None of these"], answer:1},
{q:"_____ represents an entity in the real world with its identity and behaviour.", options:["class","object","method","None of these"], answer:1},
{q:"The assignment of more than one function to a particular operator is _______", options:["Operator over-assignment","Operator overriding","Operator overloading","Operator instance"], answer:2},
{q:"__init__() methods need to be explicitly called during object creation.", options:["TRUE","FALSE"], answer:1, note:"__init__() is called automatically during object creation."},
{q:"__del__() method is used to destroy instances of a class.", options:["TRUE","FALSE"], answer:0},
{q:"What type of inheritance is illustrated in the following Python code? class A(): pass\nclass B(): pass\nclass C(A,B): pass", options:["Single inheritance","Multiple inheritance","Multilevel inheritance","Hybrid inheritance"], answer:1},
{q:"Method issubclass() checks if a class is a subclass of another class.", options:["TRUE","FALSE"], answer:0},
{q:"In Python, private members of a class are prefixed with:", options:["Single underscore","Double underscore","Triple underscore","None of these"], answer:1},
{q:"The identity of an object can be obtained using the ________ function.", options:["type()","id()","class()","object()"], answer:1},
{q:"How do you create an instance of a class named Person?", options:["person= Person.create()","person= Person()","person = new Person()","None of these"], answer:1},
{q:"How do you inherit a class in Python?", options:["class Derived = Base","class Derived: Base","class Derived(Base)","None of these"], answer:2},
],
"Section 9: Regular Expressions": [
{q:"Which module in Python is used for working with regular expressions?", options:["regexp","regex","re","rexp"], answer:2},
{q:"Which function is used to match a pattern at the beginning of a string?", options:["re.match()","re.search()","re.findall()","re.fullmatch()"], answer:0},
{q:"What does the . (dot) character in a regular expression match?", options:["Any single character except newline","Any digit","Any whitespace","Any letter"], answer:0},
{q:"Which method is used to replace occurrences of a pattern in a string?", options:["re.sub()","re.replace()","re.substitute()","re.switch()"], answer:0},
{q:"What does the \\d pattern match in a regular expression?", options:["Any digit","Any character","Any whitespace","Any word character"], answer:0},
{q:"Which function returns a list of all non-overlapping matches of a pattern in a string?", options:["re.search()","re.findall()","re.match()","None of these"], answer:1},
{q:"How do you make a regular expression case-insensitive in Python?", options:["Using re.I","Using re.CASELESS","Using re.IGNORECASE","Using re.N"], answer:2, note:"re.I is a shorthand for the same flag."},
{q:"What does the \\s pattern match in a regular expression?", options:["Any whitespace character","Any single character","Any non-whitespace character","Any digit"], answer:0},
{q:"Which method would you use to check if all characters in a string are alphabetic?", options:["isalpha()","isalphabetic()","isletters()","ischar()"], answer:0},
{q:"Which method is used to replace parts of a string with another string?", options:["replace()","substitute()","findreplace()","switch()"], answer:0},
{q:"What does the regular expression pattern ba?c* match?", options:["\"bac\"","\"baac\"","\"baccc\"","All of these"], answer:0, note:"a? allows at most one 'a'; \"baac\" has two a's so it would not match this pattern."},
{q:"Which method would you use to find the position of a substring in a string?", options:["find()","index()","position()","locate()"], answer:0},
{q:"What does the + metacharacter signify in a regular expression pattern?", options:["Matches the preceding character zero or one time","Matches the preceding character zero or more times","Matches the preceding character one or more times","Matches the preceding character exactly n times"], answer:2},
{q:"Which function splits a string by the occurrences of a pattern?", options:["re.split()","re.separate()","re.divide()","re.break()"], answer:0},
{q:"What does the ^(caret) character signify in a regular expression?", options:["Start of a string","End of a string","Any single character","Zero or more occurrences of the previous character"], answer:0},
],
"Section 10: SQL & Databases": [
{q:"The table records can be retrieved using which command?", options:["SELECT","CREATE","ALTER","MODIFY"], answer:0},
{q:"Full form of DDL is –", options:["Data Describe Language","Definition Data Language","Data Definition Language","Data Distinct Language"], answer:2},
{q:"The records and structure of a table may be removed or deleted from the database using which command?", options:["DELETE","DROP","TRUNCATE","None of these"], answer:1},
{q:"Which SQL command is used to create a new table in a database?", options:["SELECT","CREATE","ALTER","MODIFY"], answer:1},
{q:"What is the purpose of the DML command \"INSERT\" in SQL?", options:["To create a new database","To add new records to a table","To delete records from a table","To modify the structure of a table"], answer:1},
{q:"Which SQL command is used to change data in a database?", options:["SELECT","UPDATE","ALTER","MODIFY"], answer:1},
{q:"What does DML stand for in SQL?", options:["Data Definition Language","Data Distribution Language","Data Manipulation Language","Data Design Language"], answer:2},
{q:"Which DDL command is used to modify an existing table by adding, modifying, or deleting columns?", options:["SELECT","UPDATE","ALTER","MODIFY"], answer:2},
{q:"What does SQL stand for?", options:["Structured Query Language","Simple Query Language","Syntax Query Language","None of these"], answer:0},
{q:"Which command delete all data from a table but keep the table structure.", options:["DELETE","DROP","TRUNCATE","None of these"], answer:2},
{q:"Which clause is used to filter the results of a query in SQL?", options:["WHERE","FILTER","HAVING","SELECT"], answer:0},
{q:"Which method is used to fetch the next row of a query result set, returning a single sequence, or None when no more data is available?", options:["fetch()","fetchmany()","fetchall()","fetchone()"], answer:3},
{q:"How do you close a connection to an SQLite3 database?", options:["conn.close()","conn.disconnect()","conn.terminate()","conn.shutdown()"], answer:0},
{q:"What method should be called to save changes to the database?", options:["commit()","save()","apply()","store()"], answer:0},
{q:"Which method fetches all rows from the result of an executed query?", options:["fetchrows()","fetchmany()","fetchall()","fetchone()"], answer:2},
],
"Section 11: Flask & Web Development": [
{q:"What is Flask?", options:["A frontend JavaScript library","A lightweight Python web framework","A Python data analysis library","A backend database system"], answer:1},
{q:"Which of the following is true about Django?", options:["It is a microframework","It includes built-in admin functionality","It is only used for frontend development","It does not support databases"], answer:1},
{q:"Which command is used to start a Flask app?", options:["flask start","python app.py","flask run","python flask.py"], answer:2},
{q:"In Flask, which method is used to return an HTTP response?", options:["flask.response()","render()","return()","render_template()"], answer:2},
{q:"What does the Flask route() decorator do?", options:["Styles the webpage","Connects a URL rule to a Python function","Sends email notifications","None of the above"], answer:1},
{q:"Which of the following is a Jinja2 template feature used for reusing parts of a template?", options:["Functions","Macros","Classes","Modules"], answer:1},
{q:"How do you define a route in Flask?", options:["Using the @flask.route decorator","Using the @app.route decorator","Using the @route function","Using the route() method"], answer:1},
{q:"What does a route define in a Flask application?", options:["The structure of the database","The URL pattern and the associated function","The static files for the web app","The middleware for the application"], answer:1},
{q:"What is the purpose of @app.route('/<name>') in Flask?", options:["To define a route with a static URL","To define a route with a dynamic URL","To create a new Flask application","To register a middleware"], answer:1},
{q:"What is a 404 error in routing?", options:["Invalid database connection","URL not found on the server","Syntax error in the Python script","Successful HTTP request"], answer:1},
{q:"In which Flask function do you typically commit database transactions?", options:["commit()","save()","push()","update()"], answer:0},
{q:"Which of these is a feature of templates in Flask and Django?", options:["Variables can be dynamically injected","Templates must always be static","Only HTML is supported in templates","They cannot include loops or conditions"], answer:0},
{q:"What is used in Flask to check user authentication status?", options:["@authenticate","@login_required","@check_user","@user_status"], answer:1},
{q:"Which HTTP method is primarily used to submit web forms?", options:["GET","POST","PUT","DELETE"], answer:1},
{q:"What is the default port for a Flask application?", options:["5000","8000","8080","3000"], answer:0},
],
"Section 12: NumPy & Pandas": [
{q:"What does NumPy stand for?", options:["Numerical Python","Number Python","Numeric Programming","Numerical Processor"], answer:0},
{q:"Which function is used to create a NumPy array?", options:["numpy.array()","numpy.make_array()","numpy.ndarray()","numpy.list()"], answer:0},
{q:"What is the default data type of a NumPy array?", options:["Integer","Float","String","Boolean"], answer:1},
{q:"What does the df.describe() method provide?", options:["Statistical summary of numerical columns","First five rows of the DataFrame","Column data types","List of missing values"], answer:0},
{q:"Which method is used to remove duplicate rows from a DataFrame?", options:["drop_duplicates()","remove_duplicates()","unique_rows()","clean_duplicates()"], answer:0},
{q:"How do you fill missing values in a DataFrame with a constant value?", options:["fillna(value)","replace_nan(value)","fill_missing(value)","set_missing(value)"], answer:0},
{q:"Which method is used to convert a column to a specific data type in Pandas?", options:["astype()","convert()","to_type()","change_type()"], answer:0},
{q:"What does the std() function calculate?", options:["Median","Standard deviation","Variance","Correlation"], answer:1},
{q:"Which method in Pandas provides the count, mean, std, min, and max of numerical columns?", options:["numerical_summary()","describe()","summary()","statistics()"], answer:1},
{q:"How do you drop rows with missing values in Pandas?", options:["dropna()","remove_nan()","drop_missing()","delete_nan()"], answer:0},
{q:"How do you access the first 5 rows of a DataFrame?", options:["df.head()","df.show()","df.tail()","df.first()"], answer:0},
{q:"Which method is used to check for missing values in a DataFrame?", options:["missing()","check_null()","isnull()","nan_check()"], answer:2},
{q:"What is the primary data structure in Pandas for labeled data?", options:["Dataframe","List","Dictionary","Numpy array"], answer:0},
{q:"What does the shape attribute of a NumPy array return?", options:["The dimensions of the array","The data type of the array elements","The total size of the array","The flattened version of the array"], answer:0},
{q:"Which function is used to create an array of evenly spaced values in NumPy?", options:["numpy.linspace()","numpy.arange()","numpy.range()","numpy.split()"], answer:0},
],
"Section 13: Pygame": [
{q:"Which command is used to install Pygame?", options:["pip install pygame","python install pygame","pip pygame","install pygame"], answer:0},
{q:"Which function in Pygame is typically used to initialize the game engine?", options:["pygame.start()","pygame.init()","pygame.begin()","pygame.run()"], answer:1},
{q:"What is collision detection used for in a game?", options:["Detecting when the game should end","Detecting when two objects interact in the game space","Calculating the score","Changing the game's background"], answer:1},
{q:"What does the pygame.display.set_mode() function do?", options:["Creates a surface to draw on","Closes the Pygame application","Sets the background color of the game","Configures audio settings"], answer:0},
{q:"Which of these is NOT a module in Pygame?", options:["pygame.draw","pygame.sprite","pygame.sound","pygame.time"], answer:2, note:"The correct module is pygame.mixer, not pygame.sound."},
{q:"What is the main loop in a Pygame application used for?", options:["To load assets","To handle and process events","To keep the game running until the user quits","To define game logic only"], answer:2},
{q:"Which function is used to fill a surface with a solid color?", options:["pygame.color.fill()","surface.fill()","pygame.draw.fill()","pygame.fill_color()"], answer:1},
{q:"What is the correct way to load an image in Pygame?", options:["pygame.image.open()","pygame.display.load_image()","pygame.image.load()","pygame.load.image()"], answer:2},
{q:"How do you update the game display after making changes?", options:["pygame.update()","pygame.display.refresh()","pygame.display.update()","pygame.refresh()"], answer:2},
{q:"Which function is used to limit the frame rate in a Pygame application?", options:["pygame.time.set_fps()","pygame.framerate.set()","clock.tick()","pygame.set_speed()"], answer:2},
{q:"What is the purpose of the pygame.event.get() function?", options:["To add events to the queue","To handle user input and system events","To delete all pending events","To reset the game window"], answer:1},
{q:"How do you quit a Pygame application?", options:["pygame.exit()","pygame.quit()","pygame.close()","pygame.stop()"], answer:1},
{q:"Which method of the Sprite class is used to draw the sprite on the screen?", options:["draw()","blit()","render()","update()"], answer:1},
{q:"How do you check for a specific key press in Pygame?", options:["pygame.key.get_pressed()","pygame.event.get_key()","pygame.check.key()","pygame.KEYCHECK()"], answer:0},
{q:"What is the function of pygame.time.Clock()?", options:["To schedule events in the game","To manage frame rate","To measure game runtime","To initialize the Pygame library"], answer:1},
],
"Section 14: Testing, Debugging & Deployment": [
{q:"Which Python module is commonly used for unit testing?", options:["debugpy","unittest","pytest-runner","coverage"], answer:1},
{q:"Which tool is best suited for debugging Python code?", options:["flake8","pytest","pdb","tox"], answer:2},
{q:"What is the primary purpose of linting?", options:["Compiling the code","Checking the code for errors","Increasing runtime efficiency","Checking the code for stylistic errors"], answer:3},
{q:"After creating a virtual environment, how do you activate it on a Windows system?", options:["activate.bat","source venv/bin/activate",".\\venv\\Scripts\\activate","activate_win"], answer:2},
{q:"Which command is used to create a virtual environment in Python?", options:["pip install venv","python -m venv <env_name>","virtualenv create <env_name>","python3.11 --virtual <env_name>"], answer:1},
{q:"What is the main purpose of a virtual environment in Python?", options:["To speed up program execution","To isolate project dependencies","To improve memory management","To debug Python code"], answer:1},
{q:"Which service is commonly used for deploying Python web applications?", options:["AWS Elastic Beanstalk","SQLite","VS Code","MySQL Workbench"], answer:0},
{q:"Which of the following tools can be used to create Python packages for deployment?", options:["pipenv","setuptools","pytest","pdb"], answer:1},
{q:"Where can Python packages be published for public use?", options:["Docker Hub","Github","PyPI","NPM"], answer:2},
{q:"What does PEP8 recommend for adding blank lines in a Python script?", options:["One blank line between all functions","Two blank lines before top-level functions and class definitions","No blank lines between function definitions","Three blank lines between all methods"], answer:1},
{q:"Which statement is true about Flake8?", options:["It compiles Python code to bytecode.","It is a packaging tool.","It checks the code against coding standards.","It is used to manage virtual environments."], answer:2},
{q:"Which of the following is NOT recommended by PEP8?", options:["Indentation of 4 spaces","Line length limit of 79 characters","Function names in camelCase","Variables named using snake_case"], answer:2},
{q:"Which command is used to list installed packages within a virtual environment?", options:["pip freeze","pip show","pip list","pip installed"], answer:2},
{q:"Which file is commonly used to define dependencies for a Python project?", options:["requirements.txt","dependencies.json","packages.cfg","setup.cfg"], answer:0},
{q:"Which of these is correct according to PEP8 for string quotation marks?", options:["Use only single quotes for all strings","Use only double quotes for all strings","Use consistent quotes within a file","Alternate between single and double quotes randomly"], answer:2},
],
};
